trigger: none
pr:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: Maven@3
    inputs:
      jdkVersionOption: '1.8'
      publishJUnitResults: true
      goals: 'clean test'
# Add linting and other quality checks here.